### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [royranger/bwa-u4-feature-request#1]
Grade: Exceeds Expectations

Great job requesting a new feature for the Jammming app! You're thinking about all the right things here: how to make the app more appealing and personal for users, how to add features into the codebase you already have (instead of just working independently and overcomplicating or duplicating code you've already written), what you need to modify vs. write from scratch. Your idea is very smart, as personalization is hugely relevant today. The natural place to take this idea next is suggesting songs similar to the "Top Tracks' instead of just giving songs the user already knows (not saying you should do this, just saying that you're on the right track!). 

Instead of determining whether the 'Welcome' element is shown by using a CSS class, why not just use a boolean and toggle it on or off in the getUserIdAndName() function? It's not necessary to put logic like that in CSS when JS itself is made for that kind of thing. You can use a ternary statement in your JSX render function so that if the user is logged in, you show the element, else you don't. You can read about ternaries here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator. I think you can totally implement this, so I hope you take this proposal and turn it into reality!

**Comment by royranger** [comment]
Thanks very much =)
